export const GET_CONTACT_LOAD = "GET_CONTACT_LOAD";
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_FAIL = "GET_CONTACT_FAIL";
export const GET_ONE_CONTACT = "GET_ONE_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
